# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [1]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np
import warnings # 05/10/2020 Hide Warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv("../datasets/ads/Advertising.csv")

In [3]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [4]:
X = data[feature_cols]
Y = data["Sales"]

In [8]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=2, step=1)
selector = selector.fit(X,Y)

In [9]:
selector.support_

array([ True,  True, False])

In [10]:
selector.ranking_

array([1, 1, 2])

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
X_pred = X[["TV", "Radio"]]

In [13]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression()

In [14]:
lm.intercept_

2.921099912405131

In [15]:
lm.coef_

array([0.04575482, 0.18799423])

In [16]:
lm.score(X_pred, Y)

0.8971942610828957