# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [3]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv("../datasets/ads/Advertising.csv")

In [5]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [6]:
X = data[feature_cols]
Y = data["Sales"]

In [7]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, 2, step=1)
selector = selector.fit(X,Y)

In [8]:
selector.support_

array([ True,  True, False])

In [9]:
selector.ranking_

array([1, 1, 2])

In [17]:
from sklearn.linear_model import LinearRegression

In [19]:
X_pred = X[["TV", "Radio"]]

In [20]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
lm.intercept_

2.9210999124051362

In [22]:
lm.coef_

array([0.04575482, 0.18799423])

In [23]:
lm.score(X_pred, Y)

0.8971942610828956