# El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.24327622, 0.60318554, 0.72408892],
       [0.10584919, 0.56236851, 0.05975853],
       [0.30887799, 0.29100802, 0.67885865],
       [0.18020585, 0.65903446, 0.462176  ],
       [0.85023048, 0.74522111, 0.5739342 ],
       [0.57896199, 0.86265495, 0.20816652],
       [0.02019233, 0.27361025, 0.3371139 ],
       [0.54054302, 0.69888469, 0.71992822],
       [0.36972618, 0.61941294, 0.42553518],
       [0.07721486, 0.93915327, 0.48527109],
       [0.13592702, 0.91944956, 0.28000776],
       [0.01037749, 0.05480406, 0.50893094],
       [0.51850712, 0.91240845, 0.42468522],
       [0.27740363, 0.1100795 , 0.96982913],
       [0.81763758, 0.49553161, 0.97659639],
       [0.46373359, 0.23367186, 0.64050321],
       [0.83707915, 0.94965509, 0.62440261],
       [0.2289729 , 0.60970231, 0.66829221],
       [0.55967859, 0.02828568, 0.29046767],
       [0.72264686, 0.45068418, 0.14720924],
       [0.77373106, 0.75260356, 0.63793063],
       [0.25593398, 0.65074944, 0.61219348],
       [0.

In [3]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.02019233, 0.27361025, 0.3371139 ],
       [0.30887799, 0.29100802, 0.67885865]])

In [4]:
from scipy.cluster.vq import vq

In [5]:
vq(data, clust_centers)

(array([1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], dtype=int32),
 array([0.32218654, 0.40944404, 0.        , 0.43565661, 0.71440968,
        0.78821104, 0.        , 0.47087023, 0.41919574, 0.68421461,
        0.65860765, 0.27837669, 0.70333989, 0.34407788, 0.6239503 ,
        0.16952531, 0.84603657, 0.32872864, 0.53176266, 0.69235268,
        0.6563794 , 0.36967716, 0.78507106, 0.77832868, 0.3245677 ,
        0.87615251, 0.11621495, 0.81949606, 0.7222352 , 0.6565174 ]))

In [6]:
from scipy.cluster.vq import kmeans

In [7]:
kmeans(data, clust_centers)

(array([[0.19487654, 0.51759619, 0.55633953],
        [0.75214332, 0.54668191, 0.44252866]]), 0.3838735276464874)

In [8]:
kmeans(data, 2)

(array([[0.76842027, 0.534974  , 0.42119024],
        [0.21520987, 0.52826022, 0.56596239]]), 0.3836206433353544)