# El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.64794608, 0.58978154, 0.457586  ],
       [0.86418797, 0.93960306, 0.91205676],
       [0.45517333, 0.83186738, 0.85112973],
       [0.90980972, 0.74137858, 0.28493695],
       [0.55135898, 0.02933044, 0.29142465],
       [0.02745073, 0.9058125 , 0.33332778],
       [0.77050918, 0.22592456, 0.79742113],
       [0.32355707, 0.39808319, 0.51058496],
       [0.54893633, 0.46920048, 0.42631236],
       [0.06625477, 0.01840404, 0.12293609],
       [0.18495803, 0.18841901, 0.44726363],
       [0.930496  , 0.25575929, 0.99384862],
       [0.18861802, 0.63469948, 0.59330767],
       [0.93784481, 0.85932239, 0.34059446],
       [0.67945637, 0.80951088, 0.25275286],
       [0.40479666, 0.96152374, 0.15785926],
       [0.87539872, 0.06414777, 0.39982498],
       [0.65101227, 0.65018467, 0.529103  ],
       [0.09670817, 0.56969742, 0.8748495 ],
       [0.26659514, 0.19276489, 0.63348146],
       [0.8400831 , 0.32396245, 0.85072164],
       [0.72074906, 0.66361744, 0.55696167],
       [0.

In [3]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.85189291, 0.02612322, 0.0743608 ],
       [0.97521937, 0.23951825, 0.44752608]])

In [4]:
from scipy.cluster.vq import vq

In [5]:
clusters = vq(data, clust_centers)
clusters

(array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 1, 1, 1]),
 array([0.47947198, 0.84748773, 0.88556269, 0.53158014, 0.37073932,
        1.16415406, 0.40560768, 0.67363418, 0.48468668, 0.78717623,
        0.78115209, 0.54839061, 0.8922792 , 0.63007016, 0.67104692,
        0.96466619, 0.20735083, 0.52953937, 1.03121555, 0.73410734,
        0.43354272, 0.50654853, 0.63068178, 0.63688495, 0.31763306,
        0.54358635, 0.        , 0.43460089, 0.        , 0.8941544 ]))

In [6]:
labels = clusters[0]
labels

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1])

In [7]:
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.offline as ply

In [ ]:
x = []
y = []
z = []
x2 = []
y2 = []
z2 = []

for i in range(0, len(labels)):
    if(labels[i] == 0):
        x.append(data[i,0])
        y.append(data[i,1])
        z.append(data[i,2])
        
    else:
        x2.append(data[i,0])
        y2.append(data[i,1])
        z2.append(data[i,2])

cluster1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.9
    ),
    name="Cluster 0"
)


cluster2 = go.Scatter3d(
    x=x2,
    y=y2,
    z=z2,
    mode='markers',
    marker=dict(
        color='rgb(127, 127, 127)',
        size=12,
        symbol='circle',
        line=dict(
            color='rgb(204, 204, 204)',
            width=1
        ),
        opacity=0.9
    ),
    name="Cluster 1"
)
data2 = [cluster1, cluster2]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=30
    )
)

fig = go.Figure(data=data2, layout=layout)
ply.plot(fig, filename='Clusters')


In [8]:
from scipy.cluster.vq import kmeans

In [9]:
kmeans(data, clust_centers)

(array([[0.55149309, 0.14895199, 0.50973511],
        [0.59158003, 0.69692438, 0.50948822]]), 0.38784900251440213)

In [10]:
kmeans(data, 2)

(array([[0.55511363, 0.20456483, 0.5587382 ],
        [0.59603233, 0.75078951, 0.45343179]]), 0.3860151283499985)