# El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.87659532, 0.84946594, 0.80665389],
       [0.50832631, 0.82488063, 0.03974976],
       [0.87452903, 0.66726123, 0.42464426],
       [0.55064443, 0.13997127, 0.25689096],
       [0.4439469 , 0.28633252, 0.26597934],
       [0.96267033, 0.71097314, 0.84638916],
       [0.08084177, 0.85060238, 0.75782162],
       [0.95930918, 0.7998674 , 0.11616394],
       [0.520527  , 0.52484544, 0.12454543],
       [0.44194257, 0.5024586 , 0.17470478],
       [0.85431517, 0.98576438, 0.76960211],
       [0.42866587, 0.88693155, 0.4298119 ],
       [0.74221561, 0.8276227 , 0.52709867],
       [0.78358539, 0.31644482, 0.63026407],
       [0.56778585, 0.17525369, 0.25076162],
       [0.00700223, 0.70194388, 0.15008283],
       [0.53174304, 0.32053385, 0.27759205],
       [0.92670706, 0.47296533, 0.2183161 ],
       [0.1331406 , 0.90426129, 0.45482856],
       [0.1763693 , 0.00489869, 0.13744587],
       [0.99152119, 0.08430219, 0.84477493],
       [0.35030632, 0.08498854, 0.01423543],
       [0.

In [3]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.50832631, 0.82488063, 0.03974976],
       [0.87659532, 0.84946594, 0.80665389]])

In [4]:
from scipy.cluster.vq import vq

In [5]:
clusters = vq(data, clust_centers)
clusters

(array([1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 1, 0, 1, 0], dtype=int32),
 array([0.        , 0.        , 0.42324246, 0.71975131, 0.58767219,
        0.16783341, 0.79725128, 0.45809424, 0.31202609, 0.35577468,
        0.14299128, 0.40292006, 0.31094398, 0.56910081, 0.68562132,
        0.52783773, 0.5581066 , 0.57512848, 0.56511593, 0.89000583,
        0.77468492, 0.75700833, 0.30758353, 0.49442343, 0.39033928,
        0.63026806, 0.6765578 , 0.8550696 , 0.67982606, 0.66462274]))

In [6]:
labels = clusters[0]
labels

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0], dtype=int32)

In [7]:
#The plotly.plotly module is deprecated,
#please install the chart-studio package and use the
#chart_studio.plotly module instead. 
#import plotly.plotly as py
import chart_studio.plotly as py
import plotly.graph_objs as go
import plotly.offline as ply

In [8]:
x = []
y = []
z = []
x2 = []
y2 = []
z2 = []

for i in range(0, len(labels)):
    if(labels[i] == 0):
        x.append(data[i,0])
        y.append(data[i,1])
        z.append(data[i,2])
        
    else:
        x2.append(data[i,0])
        y2.append(data[i,1])
        z2.append(data[i,2])

cluster1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.9
    ),
    name="Cluster 0"
)


cluster2 = go.Scatter3d(
    x=x2,
    y=y2,
    z=z2,
    mode='markers',
    marker=dict(
        color='rgb(127, 127, 127)',
        size=12,
        symbol='circle',
        line=dict(
            color='rgb(204, 204, 204)',
            width=1
        ),
        opacity=0.9
    ),
    name="Cluster 1"
)
data2 = [cluster1, cluster2]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=30
    )
)

fig = go.Figure(data=data2, layout=layout)
#ply.plot(fig, filename='Clusters')
ply.plot(fig, filename='Clusters.html')


'Clusters.html'

In [9]:
from scipy.cluster.vq import kmeans

In [11]:
kmeans(data, clust_centers)

(array([[0.46145869, 0.50100242, 0.24054779],
        [0.69028813, 0.64498274, 0.6867664 ]]),
 0.40337524918781226)

In [10]:
kmeans(data, 2)

(array([[0.52538706, 0.323723  , 0.29406204],
        [0.56819225, 0.81673486, 0.52998899]]),
 0.38412876957789427)